export type VoiceAction =
  | "NAVIGATE_ROUTE"
  | "OPEN_CHAPTER"
  | "OPEN_LESSON"
  | "NEXT_MICROSECTION"
  | "PREV_MICROSECTION"
  | "JUMP_TO_TYPE"
  | "STORY_START"
  | "STORY_PAUSE"
  | "STORY_RESUME"
  | "TTS_START"
  | "TTS_STOP"
  | "TOGGLE_ACCESSIBILITY"
  | "SEARCH_LESSONS";

export const ALLOWLIST_ACTIONS: ReadonlySet<VoiceAction> = new Set<VoiceAction>([
  "NAVIGATE_ROUTE",
  "OPEN_CHAPTER",
  "OPEN_LESSON",
  "NEXT_MICROSECTION",
  "PREV_MICROSECTION",
  "JUMP_TO_TYPE",
  "STORY_START",
  "STORY_PAUSE",
  "STORY_RESUME",
  "TTS_START",
  "TTS_STOP",
  "TOGGLE_ACCESSIBILITY",
  "SEARCH_LESSONS",
]);

